use std::path::Path;

use ncview_rs::data::grib2_index::parse_index;

#[test]
fn noaa_indexes_are_one_based_and_keep_terminal_ranges_bounded() {
    let records = parse_index(
        Path::new("sample.idx"),
        "# generated by wgrib2\n1:0:d=2026091100:TMP:surface\n2:32:d=2026091100:RH:surface\n",
        48,
    )
    .unwrap();
    assert_eq!(records[0].length, 32);
    assert_eq!(records[1].length, 16);
    assert_eq!(records[1].raw, "2:32:d=2026091100:RH:surface");
}

#[test]
fn invalid_ordinals_and_offsets_are_rejected_before_reference_creation() {
    for index in ["0:0:bad\n", "1:20:bad\n2:10:bad\n", "1:64:past-end\n"] {
        assert!(parse_index(Path::new("sample.idx"), index, 64).is_err());
    }
}
